[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-cors==4.0.0",
    "flask==3.0.2",
    "requests==2.31.0",
    "beautifulsoup4==4.12.3",
    "instaloader>=4.14.1",
]
